server: 
  port: 8085

spring:
  jersey:
   type: filter

  data:
   mongodb:
    uri: mongodb+srv://riki:Neverwinter.2@eventsorcerer.rb95b.mongodb.net/EventSorcerer.Test?retryWrites=true&w=majority
   
  security: 
    oauth2: 
      resourceserver: 
        jwt: 
          issuer-uri: "http://localhost:8083/auth/realms/"
          jwk-set-uri: "http://localhost:8083/auth/realms/rixon/protocol/openid-connect/certs"

keycloak:
  auth-server-url: http://localhost:8085/auth
  realm: sorcerer_realm
  resource: event_sorcerer
  public-client: true