server: 
  port: 8085

spring:
  jersey:
   type: filter

  data:
   mongodb:
    uri: mongodb+srv://riki:Neverwinter.2@eventsorcerer.rb95b.mongodb.net/EventSorcerer.Test?retryWrites=true&w=majority
   
  security: 
    oauth2: 
      resourceserver: 
        jwt: 
          issuer-uri: http://localhost:8083/auth/realms/sorcerer_realm/protocol/openid-connect/token
          jwk-set-uri: http://localhost:8083/auth/realms/sorcerer_realm/protocol/openid-connect/certs

keycloak:
  realm: sorcerer_realm
  bearer-only: true
  auth-server-url: http://localhost:8083/auth/
  ssl-required: external
  resource: event_sorcerer
  verify-token-audience: true
  credentials:
    secret-jwt:
      secret: d84611c9-af79-423b-b12c-bfa7fec23e85
  use-resource-role-mappings: true
  confidential-port: 0